-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 414cfa7b2322cf1c46cd33a49e9da833ad785473
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        files: ^git-phab$
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        files: ^git-phab$
        args:
        - --max-complexity=40
-   repo: https://github.com/pre-commit/pre-commit.git
    sha: 6e5ac079273c1499add3a85d9b5394d0f1ef1520
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.2
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
